### ISSUE TITLE
'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by darkpixel** [mysociety/django-subdomain-instances#19]
Appears to be bombing in the middleware here:
```
  38.         request.is_user_instance = request.user.is_authenticated() and (

Exception Type: AttributeError at /
Exception Value: 'WSGIRequest' object has no attribute 'user'
```

**Comment by darkpixel** [comment]
It appears to be an issue with the order of ```MIDDLEWARE_CLASSES```.  You need the SessionMiddleware first, then Authentication, then MultiInstanceMiddleware.

On a side note, while trying to debug, it appears there's a difference in the migrations between the package on pypi verses GitHub.

**Comment by dracos** [comment]
I've updated the documentation to mention the positioning of the middleware, thanks. I guess an alternative would be to only set `is_user_instance` if it finds a `request.user`, but the docs was easier :)

On your other point, could you expand, git+pypi seem identical here?
```
$ diff -qr django-subdomain-instances-0.10.2 django-subdomain-instances-git
Only in django-subdomain-instances-git: .git
Only in django-subdomain-instances-git: .gitignore
Only in django-subdomain-instances-git: .travis.yml
Only in django-subdomain-instances-git: .tx
Only in django-subdomain-instances-git: CHANGES.txt
Only in django-subdomain-instances-0.10.2: PKG-INFO
Only in django-subdomain-instances-0.10.2: django_subdomain_instances.egg-info
Only in django-subdomain-instances-git/instances/locale/en/LC_MESSAGES: .gitignore
Only in django-subdomain-instances-0.10.2/instances/locale/en/LC_MESSAGES: django.mo
Only in django-subdomain-instances-git: runtests.py
Files django-subdomain-instances-0.10.2/setup.cfg and django-subdomain-instances-git/setup.cfg differ
```

Ah, I guess this is referring to the migration you've included in your PR, I'll take a look at that.

**Comment by darkpixel** [comment]
It looks like the problem is related to the new migrations in 1.7.  I didn't spend too much time on it--I just updated the migrations and continued on.

**Comment by Akashmodi371** [comment]
> It appears to be an issue with the order of `MIDDLEWARE_CLASSES`. You need the SessionMiddleware first, then Authentication, then MultiInstanceMiddleware.
> 
> On a side note, while trying to debug, it appears there's a difference in the migrations between the package on pypi verses GitHub.

Thanks for proper sequencing middleware it help me and it work
