### ISSUE TITLE
Instance keyword collision

### ISSUE THREAD

**Issue by darkpixel** [mysociety/django-subdomain-instances#21]
The 'instance' kwarg in ```InstanceFormMixin.get_form_kwargs()``` collides with instance used in Django's ```ModelFormMixin```.  This is causing self.object to return an Instance model rather than the model you are using with the form.  This specifically causes issues with ```get_success_url``` because it ends up calling ```get_absolute_url``` on an Instance model rather than the object you are using.  This ends up returning you to the Instance home page rather than the place you should be going.

**Comment by darkpixel** [comment]
Removing the entire ```get_form_kwargs``` function from the InstanceFormMixin appears to have no side effects when adding/editing forms and fixes the issue.

**Comment by dracos** [comment]
Yes, I would have said that in your initial ticket that I thought I saw but can't find now, odd – it's alluded to in the comment at https://github.com/mysociety/django-subdomain-instances/blob/e5045be003566b1365a20b6f73a1cfc5e8226139/instances/views.py#L41 . Your commit 499d92e added the `get_form_kwargs` so this isn't a bug against the current master.

**Comment by darkpixel** [comment]
That was my bad.  I was supposed to file this against my fork while I was digging through the code.
